import { Container, Flex, VStack, Heading, Text, SimpleGrid, GridItem, FormControl, FormLabel, Input, Select, Checkbox, Button, useColorMode, useColorModeValue} from '@chakra-ui/react'

const IndexPage = () => {
  const {toggleColorMode} = useColorMode()
  const bgColor = useColorModeValue("gray.50", "whiteAlpha.50")
  const secondaryTextColor = useColorModeValue("gray.600", "gray.400")
  return(
  <Container maxW="container.xl" padding={0}>
    <Flex h="100vh" py={20}>
      <VStack w="full" h="full" p={10} spacing={10} alignItems="flex-start">
        <VStack spacing={3} alignItems="flex-start">
        <Heading size="2xl">Your Details</Heading>
        <Text>If you already have an account, click here to log in</Text>
        </VStack>
        <SimpleGrid columns={2} columnGap={3} rowGap={6} w="full">
        <GridItem colSpan={1}> 
          <FormControl>
            <FormLabel>First Name</FormLabel> 
            <Input placeholder="John"/>
          </FormControl>
        </GridItem>
        <GridItem colSpan={1}> 
          <FormControl>
            <FormLabel>Last Name</FormLabel> 
            <Input placeholder="Doe"/>
          </FormControl>
        </GridItem>
        <GridItem colSpan={2}> 
          <FormControl>
            <FormLabel>Address</FormLabel> 
            <Input placeholder="777 Easy St."/>
          </FormControl>
        </GridItem>
        <GridItem colSpan={1}> 
          <FormControl>
            <FormLabel>City</FormLabel> 
            <Input placeholder="Detroit"/>
          </FormControl>
        </GridItem>
        <GridItem colSpan={1}> 
          <FormControl>
            <FormLabel>Country</FormLabel> 
            <Select>
              <option value="USA">United States of America</option>
              </Select>
          </FormControl>
        </GridItem>
        <GridItem colSpan={2}> 
          <Checkbox defaultChecked>Ship to billing address</Checkbox>
        </GridItem>
        <GridItem colSpan={2}> 
          <Button size="lg" width="full">Place Order</Button>
        </GridItem>
        </SimpleGrid>
      </VStack>
      <VStack w="full" h="full" p={10} spacing={10} alignItems="flex-start" bg={bgColor}>
        <Heading color={secondaryTextColor}>Your Cart</Heading>
        <p>This is a simple example of a Next.js page.</p>
        <Button onClick={toggleColorMode} variant="link">Dark Mode</Button>
      </VStack>
    </Flex>
  </Container>
)}

export default IndexPage
// import type { NextPage } from 'next'
// import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'

// const Home: NextPage = () => {
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <main className={styles.main}>
//         <h1 className={styles.title}>
//           Welcome to <a href="https://nextjs.org">Next.js!</a>
//         </h1>

//         <p className={styles.description}>
//           Get started by editing{' '}
//           <code className={styles.code}>pages/index.tsx</code>
//         </p>

//         <div className={styles.grid}>
//           <a href="https://nextjs.org/docs" className={styles.card}>
//             <h2>Documentation &rarr;</h2>
//             <p>Find in-depth information about Next.js features and API.</p>
//           </a>

//           <a href="https://nextjs.org/learn" className={styles.card}>
//             <h2>Learn &rarr;</h2>
//             <p>Learn about Next.js in an interactive course with quizzes!</p>
//           </a>

//           <a
//             href="https://github.com/vercel/next.js/tree/canary/examples"
//             className={styles.card}
//           >
//             <h2>Examples &rarr;</h2>
//             <p>Discover and deploy boilerplate example Next.js projects.</p>
//           </a>

//           <a
//             href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//           >
//             <h2>Deploy &rarr;</h2>
//             <p>
//               Instantly deploy your Next.js site to a public URL with Vercel.
//             </p>
//           </a>
//         </div>
//       </main>

//       <footer className={styles.footer}>
//         <a
//           href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//           target="_blank"
//           rel="noopener noreferrer"
//         >
//           Powered by{' '}
//           <span className={styles.logo}>
//             <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
//           </span>
//         </a>
//       </footer>
//     </div>
//   )
// }

// export default Home
